"""Per-tenant Coraza WAF control: engine mode and the allowlist bypass.

Both are delivered the same way -- one generated `waf.conf` per tenant,
bind-mounted read-only into that tenant's WAF container at
`/opt/coraza/config.d/99-vhsp.conf`, applied with an nginx reload.

Why that path specifically: the image's own `/templates/coraza-rules.conf`
includes `/opt/coraza/config.d/*.conf` AFTER the base `coraza.conf` (so a
`SecRuleEngine` directive here overrides the `CORAZA_RULE_ENGINE` env var
the container was created with) but BEFORE `crs-setup.conf` and the CRS
rule files (so a phase-1 allowlist rule here runs before any CRS rule
gets to inspect the request). Verified by reading that template out of
the running image rather than assuming.

The practical payoff of putting BOTH settings in a mounted file rather
than in container environment variables: changing either one needs only
a file rewrite plus `nginx -s reload`, not a container recreate. The
env-var route would mean tearing down and rebuilding a tenant's WAF
container -- and therefore a brief 502 on their live site -- every time
an operator flips a mode or edits an allowlist entry.
"""

import ipaddress
import os
import stat
from pathlib import Path

from vhsp_ctl import audit, registry
from vhsp_ctl.config import WAF_ALLOWLIST_PATH, WAF_ENGINE_MODE

# Coraza/ModSecurity's own three engine states. "On" blocks,
# "DetectionOnly" logs what it would have blocked, "Off" disables rule
# evaluation entirely (cheaper than On, and unlike removing the sidecar
# it keeps the routing path unchanged).
WAF_MODES = ("On", "DetectionOnly", "Off")

WAF_CONF_FILENAME = "waf.conf"
WAF_MODE_FILENAME = ".vhsp-waf-mode"

# Custom rule IDs live below 100000; CRS reserves 900000-999999 plus the
# 9xxxxx plugin ranges, so 10000 can't collide.
_ALLOWLIST_RULE_ID = 10000


def _tenant_dir(domain: str) -> Path:
    tenant = registry.get_tenant(domain)
    if not tenant:
        raise ValueError(f"no active tenant for domain {domain!r}")
    return Path(tenant.phpconf_host_path)


def read_allowlist() -> list[str]:
    if not WAF_ALLOWLIST_PATH.exists():
        return []
    return [ln.strip() for ln in WAF_ALLOWLIST_PATH.read_text().splitlines() if ln.strip()]


def write_allowlist(entries: list[str]) -> str | None:
    """Returns an error message, or None on success -- same "validate and
    return a message rather than raise" convention as
    fail2ban_allowlist.write_entries, since a web form handler calls it."""
    cleaned = [e.strip() for e in entries if e.strip()]
    for entry in cleaned:
        try:
            ipaddress.ip_network(entry, strict=False)
        except ValueError:
            return f"Not a valid IP or CIDR: {entry!r}"
    WAF_ALLOWLIST_PATH.parent.mkdir(parents=True, exist_ok=True)
    WAF_ALLOWLIST_PATH.write_text("\n".join(cleaned) + "\n" if cleaned else "")
    os.chmod(WAF_ALLOWLIST_PATH, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
    return None


def tenant_mode(domain: str) -> str:
    """This tenant's engine mode, defaulting to the platform-wide
    config.WAF_ENGINE_MODE for any tenant that's never been set
    explicitly -- so the deployment-level default still governs, and
    per-tenant state only exists once somebody actually chose one."""
    path = _tenant_dir(domain) / WAF_MODE_FILENAME
    if not path.exists():
        return WAF_ENGINE_MODE
    mode = path.read_text().strip()
    return mode if mode in WAF_MODES else WAF_ENGINE_MODE


def render_conf(mode: str, allowlist: list[str]) -> str:
    """The generated Coraza config for one tenant. Kept a pure function
    of its two inputs so it can be tested without a tenant, a container,
    or a filesystem."""
    lines = [
        "# Generated by vhsp_ctl/waf.py -- do not edit by hand.",
        "# Rewritten whenever a tenant's WAF mode or the operator's WAF",
        "# allowlist changes; edits here are lost on the next change.",
        "",
        f"SecRuleEngine {mode}",
    ]
    if allowlist:
        joined = ",".join(allowlist)
        lines += [
            "",
            "# Allowlist bypass. phase:1 runs before any CRS rule inspects the",
            "# request, and ctl:ruleEngine=Off disables evaluation for the rest",
            "# of THIS transaction only -- it does not change the engine's",
            "# configured mode above for anyone else. nolog because a matching",
            "# request is by definition one the operator asked not to be",
            "# examined; logging every one would fill the WAF log with traffic",
            "# nobody wanted inspected.",
            f'SecRule REMOTE_ADDR "@ipMatch {joined}" \\',
            f'    "id:{_ALLOWLIST_RULE_ID},phase:1,pass,nolog,ctl:ruleEngine=Off"',
        ]
    return "\n".join(lines) + "\n"


def write_tenant_conf(domain: str) -> Path:
    """Regenerates one tenant's waf.conf from current state. Does NOT
    reload -- callers batch a reload after writing, since an allowlist
    change rewrites every tenant's file at once."""
    path = _tenant_dir(domain) / WAF_CONF_FILENAME
    path.write_text(render_conf(tenant_mode(domain), read_allowlist()))
    # World-readable: the WAF container runs as its own `nginx` user, not
    # as the host uid that writes this, and it only ever reads the file.
    # Nothing in it is secret -- an engine mode and a list of IPs.
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
    return path


def reload_tenant(domain: str) -> bool:
    """`nginx -s reload` inside the tenant's WAF container, so a config
    change applies with no dropped connections (nginx finishes in-flight
    requests on the old workers). Returns False if the container isn't
    running -- not an error: it'll read the file on its next start
    anyway, same convergence property as every other marker file here.
    """
    from vhsp_ctl import provisioner  # local: provisioner imports this module

    tenant = registry.get_tenant(domain)
    if not tenant or not tenant.waf_container:
        return False
    client = provisioner._client()
    try:
        container = client.containers.get(tenant.waf_container)
    except Exception:
        return False
    exit_code, _ = container.exec_run(["nginx", "-s", "reload"])
    return exit_code == 0


def apply_tenant(domain: str) -> bool:
    write_tenant_conf(domain)
    return reload_tenant(domain)


def set_tenant_mode(domain: str, mode: str, actor: str = "cli") -> None:
    if mode not in WAF_MODES:
        raise ValueError(f"invalid WAF mode {mode!r} -- must be one of {WAF_MODES}")
    (_tenant_dir(domain) / WAF_MODE_FILENAME).write_text(mode + "\n")
    apply_tenant(domain)
    audit.log_action(f"tenant.waf_mode_{mode.lower()}", domain, actor)


def apply_allowlist_everywhere() -> list[str]:
    """Rewrites and reloads every active tenant's config after an
    allowlist edit. Returns the domains that couldn't be reloaded (their
    container is down) rather than raising -- one stopped tenant must not
    stop the rest from picking up the change, and those will converge on
    their own next start."""
    stale = []
    for tenant in registry.list_tenants():
        try:
            if not apply_tenant(tenant.domain):
                stale.append(tenant.domain)
        except Exception:
            stale.append(tenant.domain)
    return stale
